---
apiVersion: v1
kind: Secret
metadata:
  name: etx-admin-apikey
  namespace: aee
type: Opaque
data:
  api-key: SGVsbG9Gcm9tQVBJ  # "HelloFromAPI" base64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etx-pvc
  namespace: aee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2

---
apiVersion: v1
kind: Pod
metadata:
  name: etx-pod
  namespace: aee
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo 'Hello from AEE' > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: etx-pvc
